name: weekly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'
permissions:
  contents: write
jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib datetime time csv tabula os 
    - name: Scraping this week's data and create csvs for visualization
      run: jupyter nbconvert --to notebook --execute "pay_gap.ipynb" --stdout
    # - name: Adding today's data to larger csv
    #   run: jupyter nbconvert --to notebook --execute "2-cbp-over-time.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push